name: dl_cv_workshop
channels:
  - pytorch
  - defaults
dependencies:
  - cpuonly=2.0
  - ipympl=0.9.3
  - jupyter=1.0.0
  - matplotlib=3.8
  - pillow=10.3
  - pip=24.0
  - python=3.11
  - pytorch=2.3.0
  - scikit-learn=1.4.2
  - pip:
      - opencv-python==4.9
